using EngiFlow.Application.Abstractions.Persistence;
using EngiFlow.Application.Abstractions.Tenancy;
using EngiFlow.Application.Dashboard.Dtos;
using EngiFlow.Application.Dashboard.Queries;
using EngiFlow.Domain.Ecos;
using EngiFlow.Domain.Users;
using EngiFlow.Domain.ValueObjects;
using Xunit;

namespace EngiFlow.Application.Tests;

public sealed class DashboardApplicationTests
{
    private readonly FakeTenantProvider _tenantProvider = new();
    private readonly FakeUserRepository _users = new();
    private readonly FakeEcoRepository _ecos = new();
    private readonly GetDashboardDataQueryHandler _handler;

    public DashboardApplicationTests()
    {
        _handler = new GetDashboardDataQueryHandler(_tenantProvider, _users, _ecos);
    }

    [Fact]
    public async Task HandleAsync_ApproverRole_ReturnsApproverSpecificMetrics()
    {
        // Arrange
        var userId = UserId.New();
        var companyId = CompanyId.New();
        var user = User.Create(companyId, "approver@example.com", "Approver User", UserRole.Approver, null);
        // Using private reflection or a specialized constructor would be better if User.Create didn't support ID,
        // but looking at User.cs, Create generates a NEW ID.
        // Let's use the ID generated by the domain and set it in the provider.
        _users.Add(user);
        _tenantProvider.SetContext(companyId, user.Id);

        // Act
        var result = await _handler.HandleAsync(new GetDashboardDataQuery());

        // Assert
        Assert.Contains(result.Metrics, m => m.Label == "Waiting for your review");
        Assert.DoesNotContain(result.Metrics, m => m.Label == "Assigned to you");
    }

    [Fact]
    public async Task HandleAsync_RequesterRole_ReturnsRequesterSpecificMetrics()
    {
        // Arrange
        var companyId = CompanyId.New();
        var user = User.Create(companyId, "requester@example.com", "Requester User", UserRole.Requester, null);
        _users.Add(user);
        _tenantProvider.SetContext(companyId, user.Id);

        // Act
        var result = await _handler.HandleAsync(new GetDashboardDataQuery());

        // Assert
        Assert.Contains(result.Metrics, m => m.Label == "Authored by you");
        Assert.Contains(result.Metrics, m => m.Label == "Assigned to you");
    }

    [Fact]
    public async Task HandleAsync_AdminRole_ReturnsAdminSpecificMetrics()
    {
        // Arrange
        var companyId = CompanyId.New();
        var user = User.Create(companyId, "admin@example.com", "Admin User", UserRole.Administrator, null);
        _users.Add(user);
        _tenantProvider.SetContext(companyId, user.Id);

        // Act
        var result = await _handler.HandleAsync(new GetDashboardDataQuery());

        // Assert
        Assert.Contains(result.Metrics, m => m.Label == "SLA At Risk (>5 days)");
        Assert.Contains(result.Metrics, m => m.Label == "Open Orders Count");
        Assert.Contains(result.Metrics, m => m.Label == "Pending Activations");
    }

    [Fact]
    public async Task HandleAsync_ViewerRole_ReturnsEmptyMetricsAndActivityFeed()
    {
        // Arrange
        var companyId = CompanyId.New();
        var user = User.Create(companyId, "viewer@example.com", "Viewer User", UserRole.Viewer, null);
        _users.Add(user);
        _tenantProvider.SetContext(companyId, user.Id);

        // Act
        var result = await _handler.HandleAsync(new GetDashboardDataQuery());

        // Assert
        Assert.Empty(result.Metrics);
        Assert.Empty(result.AttentionItems);
    }

    private sealed class FakeTenantProvider : ITenantProvider
    {
        public CompanyId CurrentCompanyId { get; private set; }
        public UserId CurrentUserId { get; private set; }

        public void SetContext(CompanyId companyId, UserId userId)
        {
            CurrentCompanyId = companyId;
            CurrentUserId = userId;
        }
    }

    private sealed class FakeUserRepository : IUserRepository
    {
        private readonly List<User> _users = [];

        public void Add(User user) => _users.Add(user);

        public Task AddAsync(User user, CancellationToken cancellationToken = default)
        {
            _users.Add(user);
            return Task.CompletedTask;
        }

        public Task<int> CountAsync(UserStatus? status = null, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(status.HasValue ? _users.Count(u => u.Status == status.Value) : _users.Count);
        }

        public Task<User?> GetByIdAsync(UserId id, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(_users.FirstOrDefault(u => u.Id == id));
        }

        public Task<User?> GetByNormalizedEmailAsync(string normalizedEmail, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        public Task<User?> GetOwnerByCompanyIdForAuthenticationAsync(CompanyId companyId, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        public Task<IReadOnlyList<User>> ListByEmailForAuthenticationAsync(string normalizedEmail, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        public Task<IReadOnlyList<User>> SearchAsync(string term, int limit, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        public Task<User?> GetByIdForAuthenticationAsync(UserId id, CancellationToken cancellationToken = default) => GetByIdAsync(id, cancellationToken);
        public Task RecordSuccessfulLoginAsync(UserId id, DateTimeOffset occurredAt, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task SetPasswordAndActivateAsync(UserId id, string passwordHash, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task<IReadOnlyList<User>> ListActiveAsync(CancellationToken cancellationToken = default) => Task.FromResult<IReadOnlyList<User>>(_users);
        public Task<IReadOnlyList<User>> ListForAdministrationAsync(CancellationToken cancellationToken = default) => Task.FromResult<IReadOnlyList<User>>(_users);
    }

    private sealed class FakeEcoRepository : IEngineeringChangeOrderRepository
    {
        public Task AddAsync(EngineeringChangeOrder eco, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        
        public Task<int> CountAsync(EcoListFilter? filter = null, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(0);
        }

        public Task<EngineeringChangeOrder?> GetByIdAsync(EngineeringChangeOrderId id, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        public Task<EngineeringChangeOrder?> GetByIdWithEventsAsync(EngineeringChangeOrderId id, CancellationToken cancellationToken = default) => throw new NotImplementedException();
        
        public Task<IReadOnlyList<EngineeringChangeOrder>> ListAsync(int pageNumber, int pageSize, EcoListFilter? filter = null, CancellationToken cancellationToken = default)
        {
            return Task.FromResult<IReadOnlyList<EngineeringChangeOrder>>([]);
        }

        public Task<IReadOnlyList<EcoActivityDto>> ListRecentActivityAsync(int limit, CancellationToken cancellationToken = default)
        {
            return Task.FromResult<IReadOnlyList<EcoActivityDto>>([]);
        }
    }
}
