using EngiFlow.Application.Notifications.Dtos;

namespace EngiFlow.Api.Hubs;

/// <summary>
/// Client contract for user-scoped real-time notification messages.
/// </summary>
public interface INotificationClient
{
    /// <summary>
    /// Receives a new notification generated by the backend.
    /// </summary>
    /// <param name="notification">The notification payload.</param>
    Task ReceiveNotification(NotificationDto notification);
}
